### ISSUE TITLE
mj-api-secret 为空时出错

### ISSUE THREAD

**Issue by tkizm1** [Dooy/chatgpt-web-midjourney-proxy#295]
```
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "mj-api-secret"
    at ClientRequest.setHeader (node:_http_outgoing:662:3)
    at new ClientRequest (node:_http_client:289:14)
    at Object.request (node:http:103:10)
    at /app/node_modules/.pnpm/express-http-proxy@2.0.0/node_modules/express-http-proxy/app/steps/sendProxyRequest.js:13:51
    at new Promise (<anonymous>)
    at sendProxyRequest (/app/node_modules/.pnpm/express-http-proxy@2.0.0/node_modules/express-http-proxy/app/steps/sendProxyRequest.js:11:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Dooy** [comment]
收到 手续修复下

**Comment by Dooy** [comment]
已经修复 下更新至 `v2.17.1`
