### ISSUE TITLE
8-24 最新镜像有问题

### ISSUE THREAD

**Issue by Aiurvie** [Dooy/chatgpt-web-midjourney-proxy#493]
8.24 的镜像好像有问题。
配置好启动之后，直接交互会导致容器退出。
而如果在容器启动后，在网页上进行配置，则不会有这个问题。

确定 Server & Key 配置正确，退出时，异常信息为：
```
 WARN  Unsupported engine: wanted: {"node":"^16 || ^18 || ^19"} (current: {"node":"v20.17.0","pnpm":"9.8.0"})

> chatgpt-web-service@2.15.6 prod /app
> node ./build/index.mjs

Server is running on port 3002
(node:18) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
file:///app/build/index.mjs:283
  const auth_secret_keys = AUTH_SECRET_KEY.trim().split(",").filter((item) => item !== "");
                                           ^

TypeError: Cannot read properties of undefined (reading 'trim')
    at authV2 (file:///app/build/index.mjs:283:44)
    at Layer.handle [as handle_request] (/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:280:10)
    at next (/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:136:14)
    at next (/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:140:7)
    at next (/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:140:7)
    at next (/app/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:140:7)

Node.js v20.17.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Dooy** [comment]
好的 最近 是修改过 这儿

**Comment by Dooy** [comment]
重新pull 下， 我修复了 没有发新的版本
